language: python
python:
    - "2.7"
# before_install:
#	- sudo apt-get -qq update
#	- sudo apt-get install -y
install: 
#    - "python setup.py install"
    - "pip install -r requirements.txt --use-mirrors"
# command to run tests
script: "tests/run-tests.sh"
